# Generated by Django 3.0.8 on 2020-08-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20200803_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
