# Generated by Django 3.0.8 on 2020-08-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_breeds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breeds',
            new_name='Breed',
        ),
    ]
