# Generated by Django 3.0.8 on 2020-08-05 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20200805_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='picture',
            field=models.FileField(default=datetime.datetime(2020, 8, 5, 8, 12, 41, 381249, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
