# Generated by Django 3.0.8 on 2020-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_breed_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='alternative_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='lifespan',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='origin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='picture',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
